# Generated by Django 6.0.5 on 2026-05-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('mother_name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=16)),
            ],
        ),
    ]
